imersaoPython/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/clearcache/', include('clearcache.urls')),
    path('admin/', admin.site.urls),
    path("",include('produto.urls')),
    path("pedido",include('pedido.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls)),]

pedido/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'Pedido'

urlpatterns = [
    path("finalizar_pedido/", views.finalizar_pedido, name='finalizar_pedido'),
    path("validaCupom/", views.validaCupom, name='validaCupom'),
    path("freteBairro/", views.freteBairro, name='freteBairro'),
    path("novo/",views.novo,name='novo'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

produto/urls.py
from django.urls import path
from . import views,htmx_views
from django.urls import path
from django.contrib.sitemaps.views import sitemap
from produto.views import robots,Sitemap

app_name = 'Core'

sitemaps = {
    'sitemap': Sitemap,
}

urlpatterns = [
    path("", views.home, name="home"),
    path("loja/", views.loja, name="loja"),
    path("contact/", views.contact, name='contact'),
    path("formulario/", views.formulario, name='formulario'),
    path('unsubscriber/<int:id>',views.unsubscriber, name='unsubscriber'),
    path("categoria/<str:nome>", views.categorias, name='categoria'),
    path("produto/<int:id>", views.produto, name='produto'),
    path("add_carrinho", views.add_carrinho, name='add_carrinho'),
    path("ver_carrinho", views.ver_carrinho, name='ver_carrinho'),
    path("remover_carrinho/<int:id>", views.remover_carrinho, name='remover_carrinho'),
    path('total_vendas',views.total_vendas,name='total_vendas'),
    path('ticket_medio',views.ticket_medio,name='ticket_medio'),
    path('mais_vendidos',views.mais_vendidos,name='mais_vendidos'),
    path('bairro_mais_pedido',views.bairro_mais_pedido,name='bairro_mais_pedido'),
    path('vendas_ultimos_12_meses',views.vendas_ultimos_12_meses,name='vendas_ultimos_12_meses'),
    path('dashbords/',views.dashbords, name='dashbords'),
    path('enviar_emeil/',views.enviar_emeil, name='enviar_emeil'),
    path('robots.txt',robots),
    path('sitemap.xml',sitemap, {'sitemaps': sitemaps}),
]

htmx_patterns =[
    path('search/',htmx_views.search, name='search'),
   # path('status/',htmx_views.status, name='status'),
]

urlpatterns += htmx_patterns

produto/models.py
from django.db import models
from django.urls import reverse
from django.utils.safestring import mark_safe

class Categoria(models.Model):
    categoria = models.CharField(max_length=200)

    def __str__(self):
        return self.categoria
    
class Bairro(models.Model):
    Nome = models.CharField(max_length=100)
    Frete = models.FloatField()

    def __str__(self):
        return self.Nome

class Opcoes(models.Model):
    nome = models.CharField(max_length=100)
    acrecimo = models.FloatField(default=0)
    ativo = models.BooleanField(default=True)
    def __str__(self):
        return self.nome
    
    class Meta:
        verbose_name_plural = "Opçôes"

class Adicional(models.Model):
    nome = models.CharField(max_length=100, unique=True)
    maximo = models.IntegerField()
    minimo = models.IntegerField()
    opcoes = models.ManyToManyField(Opcoes)
    ativo = models.BooleanField(default=True)
    def __str__(self):
        return self.nome
    
    class Meta:
        verbose_name_plural = "Adicionais"

class Produto(models.Model):
    nome_produto = models.CharField(max_length=100)
    img = models.ImageField(upload_to='post_img')
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    preco = models.FloatField()
    descricao = models.TextField()
    ingredientes = models.CharField(max_length=2000)
    adicionais = models.ManyToManyField(Adicional, blank=True)
    promocao=models.BooleanField(default=False)
    ativo = models.BooleanField(default=True)
    data_upload = models.DateTimeField(auto_now_add=True)

    def get_absolute_url(self):
        return reverse('Core:produto', args=[str(self.id)]) 

    @mark_safe
    def icone(self):
        return f'<img width="30px" src="{self.img.url}">'


    def __str__(self):
        return self.nome_produto
    
class Contato(models.Model):
    Nome = models.CharField(max_length=100,null=True, blank=True)
    Email = models.EmailField()
    Telefone = models.IntegerField()
    Mensagem = models.TextField(max_length=500)
    Lido = models.BooleanField(default=False)
    
    def __str__(self):
        return self.Nome
    
    class Meta:
        verbose_name_plural = "Contatos"

class Email(models.Model):
    email = models.EmailField()
    ativo = models.BooleanField(default=True)

    def __str__(self) -> str:
        return self.email
    
    class Meta:
        verbose_name_plural = "Newsletter"

class Unidade(models.Model):
    nome = models.CharField(max_length=100,null=True, blank=True)
    logo = models.ImageField(upload_to='unidade_img')
    imagem = models.ImageField(upload_to='unidade_img')
    endereco= models.CharField(max_length=100,null=True, blank=True)
    horario_de = models.TimeField(auto_now=False, auto_now_add=False)
    horario_ate = models.TimeField(auto_now=False, auto_now_add=False)
    ativo = models.BooleanField(default=True)

    def __str__(self) -> str:
        return self.nome
    class Meta:
        verbose_name_plural = "Unidade"

produto/views.py
from django.contrib.messages import constants
from django.http import HttpResponse,JsonResponse
import os
from django.shortcuts import render,redirect,get_object_or_404
from django.core.paginator import Paginator
from .models import Produto, Categoria, Opcoes, Adicional,Contato,Email,Unidade
from pedido.models import Pedido,ItemPedido
from django.contrib import messages
from django.db import transaction
from django.views.decorators.cache import cache_page
from django.core.cache import cache
import datetime
from django.db.models import Count,Sum
from django.db.models.functions import TruncMonth
import logging
from django.conf import settings
from django.contrib import sitemaps
from .utils import email_html
from django.contrib.auth.decorators import login_required
from calendar import monthrange
from datetime import datetime, date
from django.utils.timezone import now,timedelta

#from channels.layers import get_channel_layer
#from asgiref.sync import async_to_sync

logger = logging.getLogger('Aplicacao')

def primeiro_dia_mes():
    data_atual = date.today()
    primeiro_dia = data_atual.replace(day=1)
    return primeiro_dia

def ultimo_dia_mes():
    data_atual = date.today()
    last_date = data_atual.replace(day=1) + timedelta(monthrange(data_atual.year, data_atual.month)[1] - 1)
    return last_date


def get_status():
    status = Unidade.objects.last()
    return status

def get_categorias_com_contagem():
    cached_categorias = cache.get('all_categorias_com_contagem')
    if cached_categorias is None:
        categorias = Categoria.objects.annotate(quantidade=Count('produto')).values('id', 'categoria', 'quantidade')
        cached_categorias = [{'id': cat['id'], 'categoria': cat['categoria'], 'quantidade': cat['quantidade']} for cat in categorias]
        cache.set('all_categorias_com_contagem', cached_categorias, timeout=1800)
    return cached_categorias

def get_all_produtos():
    cached_produtos = cache.get('all_produtos')
    if cached_produtos is None:
        produtos = Produto.objects.filter(ativo=True).only('id', 'nome_produto', 'img', 'descricao','promocao','preco','categoria').order_by('-id')
        cached_produtos = [{'id': produto.id, 'nome_produto': produto.nome_produto, 'img': produto.img, 'descricao': produto.descricao,'promocao':produto.promocao, 'preco': produto.preco, 'categoria':produto.categoria} for produto in produtos]
        cache.set('all_produtos', cached_produtos, timeout=1800)
    return cached_produtos

def get_produtos_com_promocao():
    cached_promo = cache.get('all_produtos_com_promocao')
    if cached_promo is None:
        promos = Produto.objects.only('nome_produto','img','descricao').filter(ativo=True,promocao=True).all().order_by('-id')
        cached_promo = [{'nome_produto': produto.nome_produto, 'img': produto.img, 'descricao': produto.descricao} for produto in promos]
        cache.set('all_produtos_com_promocao', cached_promo, timeout=1800)
    return cached_promo

def home(request):
    status = get_status()
    categorias = get_categorias_com_contagem()
    if not request.session.get('carrinho'):
        request.session['carrinho'] = []
        request.session.save()
    produtos = get_all_produtos()
    promos = get_produtos_com_promocao()
    pagina = Paginator(produtos,15)
    pg_number = request.GET.get('page')
    paginas = pagina.get_page(pg_number)
    return render(request, 'home.html', {'produtos': paginas,
                                        'carrinho': len(request.session['carrinho']),
                                        'categorias': categorias,
                                        'promos':promos,
                                        'status':status,
                                        })

def loja(request):
    status = get_status()
    categorias = get_categorias_com_contagem()
    if not request.session.get('carrinho'):
        request.session['carrinho'] = []
        request.session.save()
    return render(request, 'loja.html', {
                                        'carrinho': len(request.session['carrinho']),
                                        'categorias': categorias,
                                        'status':status,
                                        })

def categorias(request, nome):
    status = get_status()
    categorias = get_categorias_com_contagem()
    if not request.session.get('carrinho'):
        request.session['carrinho'] = []
        request.session.save()
    categoria_nome = get_object_or_404(Categoria, categoria=nome)
    produtos =Produto.objects.filter(ativo=True,categoria=categoria_nome).only('id', 'nome_produto', 'img', 'descricao','promocao','preco').order_by('-id')
    pagina = Paginator(produtos,15)
    pg_number = request.GET.get('page')
    paginas = pagina.get_page(pg_number)

    return render(request, 'home.html', {'produtos': paginas,
                                        'carrinho': len(request.session['carrinho']),
                                        'categorias': categorias,
                                        'status':status,
                                        })

@transaction.atomic
def produto(request, id):
    status = get_status()
    if not request.session.get('carrinho'):
        request.session['carrinho'] = []
        request.session.save()


    produto = Produto.objects.filter(id=id)[0]
    categorias = get_categorias_com_contagem()
    return render(request, 'produto.html', {'produto': produto,
                                            'carrinho': len(request.session['carrinho']),
                                            'categorias': categorias,
                                            'status':status,
                                           })

@transaction.atomic
def add_carrinho(request):
    if not request.session.get('carrinho'):
        request.session['carrinho'] = []
        request.session.save()

    x = dict(request.POST)

    def removeLixo():
        adicionais = x.copy()
        adicionais.pop('id')
        adicionais.pop('csrfmiddlewaretoken')
        adicionais.pop('observacoes')
        adicionais.pop('quantidade')
        adicionais = list(adicionais.items())

        return adicionais

    adicionais = removeLixo()

    id = int(x['id'][0])
    preco_total = Produto.objects.filter(id=id)[0].preco
    adicionais_verifica = Adicional.objects.filter(produto=id)
    aprovado = True

    for i in adicionais_verifica:
        encontrou = False
        minimo = i.minimo
        maximo = i.maximo
        for j in adicionais:
            if i.nome == j[0]:
                encontrou = True
                if len(j[1]) < minimo or len(j[1]) > maximo:
                    aprovado = False
        if minimo > 0 and encontrou == False:
            aprovado = False

    if not aprovado:
        logger.warning(f'Confira a quantidade de adicionais selecionados'+str(datetime.datetime.now())+' horas!')
        messages.add_message(request, constants.ERROR, 'Confira a quantidade de adicionais selecionados')
        return redirect(f'/produto/{id}')

    for i, j in adicionais:
        for k in j:
            preco_total += Opcoes.objects.filter(id=int(k))[0].acrecimo

    def troca_id_por_nome_adicional(adicional):
        adicionais_com_nome = []
        for i in adicionais:
            opcoes = []
            for j in i[1]:
                op = Opcoes.objects.filter(id=int(j))[0].nome
                opcoes.append(op)
            adicionais_com_nome.append((i[0], opcoes))
        return adicionais_com_nome

    adicionais = troca_id_por_nome_adicional(adicionais)

    preco_total *= int(x['quantidade'][0])
    data = {'id_produto': int(x['id'][0]),
            'observacoes': x['observacoes'][0],
            'preco': preco_total,
            'adicionais': adicionais,
            'quantidade': x['quantidade'][0]}

    request.session['carrinho'].append(data)
    request.session.save()

    return redirect(f'/ver_carrinho')


def ver_carrinho(request):
    status = get_status()
    categorias = get_categorias_com_contagem()
    dados_motrar = []
    for i in request.session['carrinho']:
        prod = Produto.objects.filter(id=i['id_produto'])
        dados_motrar.append(
            {'imagem': prod[0].img.url,
             'nome': prod[0].nome_produto,
             'quantidade': i['quantidade'],
             'observacoes': i['observacoes'],
             'preco': i['preco'],
             'id': i['id_produto']
             }
        )
    total = sum([float(i['preco']) for i in request.session['carrinho']])

    return render(request, 'carrinho.html', {'dados': dados_motrar,
                                             'total': total,
                                             #'carrinho': len(request.session['carrinho']),
                                             'categorias': categorias,
                                             'status':status,
                                             })

def remover_carrinho(request, id):
    request.session['carrinho'].pop(id)
    request.session.save()
    return redirect('/ver_carrinho')

#def fechar_loja(request):
#    channel_layer = get_channel_layer()
#    async_to_sync(channel_layer.group_send)(
#        'public_room',
#        {
#            'type': 'update_store_status',
#            'status': 'closed'
#        }
#    )
#    messages.add_message(request, constants.SUCCESS, 'Loja fechada com sucesso')
#    return redirect('/')

#def abrir_loja(request):
#    channel_layer = get_channel_layer()
#    async_to_sync(channel_layer.group_send)(
#        'public_room',
#        {
#            'type': 'update_store_status',
#            'status': 'open'
#        }
#    )
#    messages.add_message(request, constants.SUCCESS, 'Loja Aberta com sucesso')
#    return redirect('/')


@transaction.atomic
def contact(request):
    categorias = get_categorias_com_contagem()
    if not request.session.get('carrinho'):
        request.session['carrinho'] = []
        request.session.save()

produto/templates/carrinho.html
{%extends 'base.html'%}

{% load filtros %}
{% block 'title' %}Carrinho{% endblock %}
{% block 'conteudo'%}
<br>
<br>
<div class="container-fluid text-center" style="overflow-x:auto;" >
<table class="table table-striped">
    <thead>
      <tr>
        <th>Imagem</th>
        <th>Produto</th>
        <th>QTD.</th>
        <th>Obervaçao</th>
        <th>Sub total</th>
        <th>Remover</th>
      </tr>
    </thead>
    <tbody>
    {% for j, i in dados|enumerate%}
      <tr>
        <th><img src="{{i.imagem}}" width="50px"></th>
        <td>{{i.nome}}</td>
        <td>{{i.quantidade}}</td>
        <td>{{i.observacoes|slice:":20"}}</td>
        <td>R${{i.preco}}0</td>
        <td><a href="{% url 'Core:remover_carrinho' j%}" class="btn btn-danger">Remover</a></td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  <h1 class="titulo">Total: </h1>
  <h2 style="color: gray;">&nbsp R${{total}}0</h2>


  <a href="{% url 'Pedido:finalizar_pedido' %}" class="btn btn-success loja-fechada">Finalizar compra</a>
  <a href="{% url 'Core:home'%}" class="btn btn-primary" style="margin: 5px;">Continuar comprando</a>

</div>
{%endblock%}

produto/templates/contact.html
{% extends 'base.html' %}
{% load static %}
{% block 'title' %}Contatos{% endblock %}

 {% block 'cabeca' %}
 {% endblock %}

 {% block 'conteudo' %}
 <br>
 
 <div class="container">
    {% if messages %}
        {% for message in messages %}
            <div class="text-center alert {{message.tags}}">
                {{message}}
            </div>
        {% endfor %}
    {% endif %}
</div>
 <div class="container-fluid">
    <div class="justify-content-center text-center">
        <main class="mb-4">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                       <p style="color:var(--vermelho)"> Quer entrar em contato? Preencha o formulário abaixo para me enviar uma mensagem e entrarei em contato com você o mais breve possível!</p>
                        <div class="my-5">
                            <form method="POST"  id="contactForm" action="{% url 'Core:contact'%}">{% csrf_token %}
                                <label for="name" style="color:var(--vermelho)">Nome</label>
                                <div class="form-floating">
                                    <input class="form-control" id="name" name="name" type="text" placeholder="Entre com seu Nome" required  />
                                </div>
                                <div class="invalid-feedback" data-sb-feedback="name:required">Um nome e Obrigatorio!</div>
                                <br>
                                <label for="email" style="color:var(--vermelho)">Endereco de Email</label>
                                <div class="form-floating">
                                    <input class="form-control" id="email" name="email" type="email" placeholder="Entre com seu email..." required />
                                </div>
                                <br>
                                <label for="phone" style="color:var(--vermelho)">Telefone</label>
                                <div class="form-floating">
                                    <input class="form-control" id="phone" name="phone" type="tel" placeholder="Entre com seu Telefone..." required />
                                </div>
                                <br>
                                <label for="phone" style="color:var(--vermelho)">Entre com sua Mensagem aqui...</label>
                                
                                <div class="form-floating">
                                    <textarea class="form-control" id="message" name="message" placeholder="Entre com sua Mensagem aqui..." style="height: 12rem" rows="4" cols="50" maxlength="500" required></textarea>
                                    <br>
                                </div>
                                <br/>
                                <div class="text-center">
                                <button class="btn btn-success text-uppercase" id="submitButton" type="submit">Enviar</button>
                            </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </main>
 </div>
 </div>
 {% endblock %}

produto/templates/produto.html
{%extends 'base.html'%}

{%block 'head'%}
<script src="https://code.jquery.com/jquery-3.4.1.js"></script>
{%endblock%}

{% block 'title' %}Produto {{produto.nome_produto}} {% endblock %}

{% block 'conteudo'%}
<div class="container-fluid" style="align-items: center; text-align: center;">
    <br>
    <div class="container">
        {% if messages%}
        {% for i in messages%}
        <div class="alert {{i.tags}}" role="alert">
            {{i}}
        </div>
        {%endfor%}
        {%endif%}

    </div>
    <img class="tamanhoImg" style="margin-top: 20px;" src="{{produto.img.url}}">

    <h3  class="titulo tituloProduto">{{produto.nome_produto}}</h3>
  
    <h1 class="titulo subTituloProduto">Descrição: </h1>
    <h3 style="color: gray;">{{produto.descricao}}</h3>
    <h1 class="titulo subTituloProduto">Ingredientes: </h1>
    <h3 style="color: gray;">{{produto.ingredientes}}</h3>

    <h1 class="titulo subTituloProduto">Adicionais: </h1>

    <form method="POST" action="{% url 'Core:add_carrinho' %}">{% csrf_token %}
    <input name="id" style="display: none;" type="text" value="{{produto.id}}">

    {% for i in produto.adicionais.all %}
    <h1>{{i}}</h1>
    <p>Escolha no mínimo {{i.minimo}} e no máximo {{i.maximo}} {{i}}</p>
        {%for j in i.opcoes.all%}
            {%if j.ativo%}
                <div>
                <input type="checkbox" class="checkbox" name="{{i}}" value={{j.id}}>
                <label for="scales">&nbsp&nbsp&nbsp{{j}} + R${{j.acrecimo}}</label>
                </div>
                <br>
            {%endif%}
        {%endfor%}
    {% endfor %}

    <h1 class="titulo subTituloProduto">Observações: </h1>
    <textarea  name="observacoes" class="observacoes" rows="3" type="text"></textarea>

    <h1 class="titulo subTituloProduto">Quantidade: </h1>
    <input name="quantidade" class="observacoes" type="number"  min="1" max="200" value="1">

    <h1 class="titulo subTituloProduto">Preço: </h1>
    <h3>R${{produto.preco}} Unidade</h3>

    <input class="botao botao loja-fechada" type="submit" value="Adicionar carrinho">

</form>
<br>
</div>


{%endblock%}