imersaoPython/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/clearcache/', include('clearcache.urls')),
    path('admin/', admin.site.urls),
    path("",include('produto.urls')),
    path("pedido",include('pedido.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls)),]

pedido/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'Pedido'

urlpatterns = [
    path("finalizar_pedido/", views.finalizar_pedido, name='finalizar_pedido'),
    path("validaCupom/", views.validaCupom, name='validaCupom'),
    path("freteBairro/", views.freteBairro, name='freteBairro'),
    path("novo/",views.novo,name='novo'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

produto/urls.py
from django.urls import path
from . import views,htmx_views
from django.urls import path
from django.contrib.sitemaps.views import sitemap
from produto.views import robots,Sitemap

app_name = 'Core'

sitemaps = {
    'sitemap': Sitemap,
}

urlpatterns = [
    path("", views.home, name="home"),
    path("loja/", views.loja, name="loja"),
    path("contact/", views.contact, name='contact'),
    path("formulario/", views.formulario, name='formulario'),
    path('unsubscriber/<int:id>',views.unsubscriber, name='unsubscriber'),
    path("categoria/<str:nome>", views.categorias, name='categoria'),
    path("produto/<int:id>", views.produto, name='produto'),
    path("add_carrinho", views.add_carrinho, name='add_carrinho'),
    path("ver_carrinho", views.ver_carrinho, name='ver_carrinho'),
    path("remover_carrinho/<int:id>", views.remover_carrinho, name='remover_carrinho'),
    path('total_vendas',views.total_vendas,name='total_vendas'),
    path('ticket_medio',views.ticket_medio,name='ticket_medio'),
    path('mais_vendidos',views.mais_vendidos,name='mais_vendidos'),
    path('bairro_mais_pedido',views.bairro_mais_pedido,name='bairro_mais_pedido'),
    path('vendas_ultimos_12_meses',views.vendas_ultimos_12_meses,name='vendas_ultimos_12_meses'),
    path('dashbords/',views.dashbords, name='dashbords'),
    path('enviar_emeil/',views.enviar_emeil, name='enviar_emeil'),
    path('robots.txt',robots),
    path('sitemap.xml',sitemap, {'sitemaps': sitemaps}),
]

htmx_patterns =[
    path('search/',htmx_views.search, name='search'),
   # path('status/',htmx_views.status, name='status'),
]

urlpatterns += htmx_patterns

templates/base.html
{% load static %}

{% load cache %}

{% cache 3600 cache_base-1 %}

<!doctype html>
<html lang="pt-BR">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="shortcut icon" href="{{status.logo.url}}" type="image/x-icon" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" >
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="{% static 'produto/css/css.css' %}" >
    <script src="https://unpkg.com/htmx.org@1.9.10" integrity="sha384-D1Kt99CQMDuVetoL1lrYwg5t+9QdHe7NLX/SoJYkXDFfX37iInKRy5xLSi8nO7UC" crossorigin="anonymous"></script>

    {% endcache %}
    <title>{% block 'title' %}
      {% endblock %}</title>

    {% block 'head'%}

    {% endblock %}

  </head>
  <body>
    {% cache 3600 cache_base-2 %}

    <nav class="navbar navbar-expand-lg navbar-light corBorda">
        <a class="navbar-brand" href="{% url 'Core:home'%}"><img src="{{status.logo.url}}" height="80px" alt="lanches-gulao">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav">

            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Categorias
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                 {% for categoria in categorias %}
                <a class="dropdown-item" href="{% url 'Core:categoria' categoria.categoria %}">{{categoria.categoria}} <span class="badge badge-danger">{{categoria.quantidade}}</span></a>
                {%endfor%}
              </div>
            </li>
              <li>
                  <a class="nav-link " href="{% url 'Core:loja'%}"  role="button">
                Sobre nos
              </a>
              </li>
              <li>
                  <a class="nav-link " href="{% url 'Core:contact'%}"  role="button">
                      Contatos
                  </a>
              </li>
              <li>
                <a class="nav-link " href="{% url 'Pedido:novo'%}"  role="button">
                    Novo
                </a>
            </li>
          </ul>
      

        </div>

      
      </nav>
      {% endcache %}
      <br>
      <div class="container-fluid text-center">
      {% include 'particials/htmx_componenntes/check_status.html' %}
    </div>
      <br>
      
      <div id="carouselExampleCaptions" class="carousel slide container-fluid" data-ride="carousel">
        <ol class="carousel-indicators">
          {% for promo in promos %}
          <li data-target="#carouselExampleCaptions" data-slide-to="{{ forloop.counter0 }}" {% if forloop.first %} class="active" {% endif %}></li>
          {% endfor %}
        </ol>
        <div class="carousel-inner">
          {% for promo in promos %}
          <div class="carousel-item {% if forloop.first %} active {% endif %}">
            <img src="{{ promo.img.url }}" class="d-block w-100" style="height:350px; width: 100%; background-size: cover;background-position: center;"  alt="{{promo.img.url}}">
            <div class="carousel-caption d-none d-md-block">
              <h5 class="promo">{{ promo.nome_produto }}</h5>
              <p class="promo">{{ promo.descricao }}</p>
            </div>
          </div>
          {% endfor %}
        </div>
        <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>

      {% block 'conteudo' %}


      {% endblock %}

      
      {% if carrinho %}     <a class="nav-item my-cart-icon" href="{%url 'Core:ver_carrinho'%}"><img width="25" height="25" src="https://img.icons8.com/glyph-neue/64/shopping-cart.png" alt="shopping-cart"/><span class="badge badge-pill badge-danger">{{carrinho}}</span>
    </a>
    {% endif%}
        <div class="container">
          {% if messages %}
              {% for message in messages %}
                  <div class="text-center alert {{message.tags}}">
                      {{message}}
                  </div>
              {% endfor %}
          {% endif %}
      </div>
        <br>
        <div class="container-fluid text-center">
          {% include 'particials/htmx_componenntes/check_status.html' %}
        </div>
        <footer class="bg-body-tertiary text-center">
          <!-- Grid container -->
          <div class="container p-4">
    {% cache 3600 cache_footer-1 %}
    <!-- Section: Social media -->
    <section class="mb-4">
      <!-- Facebook -->
      <a data-mdb-ripple-init class="btn btn-outline btn-floating m-1" href="#!" role="button"
        ><i class="fab fa-facebook-f"></i
      ></a>

      <!-- Instagram -->
      <a data-mdb-ripple-init class="btn btn-outline btn-floating m-1" href="https://www.instagram.com/lanches.gulao/" role="button"
        ><i class="fab fa-instagram"></i
      ></a>

    </section>
    <!-- Section: Social media -->
    {% endcache %}
    <!-- Section: Form -->
    <section class="">
      <form method="POST"  action="{% url 'Core:formulario' %}">{% csrf_token %} 
        <!--Grid row-->
        <div class="row d-flex justify-content-center">
          <!--Grid column-->
          <div class="col-auto">
            <p class="pt-2">
              <strong>Não perca nossas promoções</strong>
            </p>
          </div>
          <!--Grid column-->

          <!--Grid column-->
          <div class="col-md-5 col-12">
            <!-- Email input -->
            <div data-mdb-input-init class="form-outline mb-4">
              <form  action="" class="form-inline">
                <input type="email" name="email" id="email" class="form-control" placeholder="Email" />
            </div>
          </div>
          <!--Grid column-->

          <!--Grid column-->
          <div class="col-auto">
            <!-- Submit button -->
            <button data-mdb-ripple-init type="submit" class="btn btn-outline mb-4 btn-primary">
              Se inscrever
            </button>
          </div>
          <!--Grid column-->
        </div>
        <!--Grid row-->
      </form>
      <span class="font-medium">{{status.endereco}}</span>
    </section>
    <!-- Section: Form -->
    {% cache 3600 cache_footer-2 %}
    <!-- Section: Text -->
    <section class="mb-4">
      <p>
      </p>
    </section>
    <!-- Section: Text -->

    <!-- Section: Links -->
    <section class="">
      <!--Grid row-->
      <div class="row">
        <!--Grid column
        <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
          <h5 class="text-uppercase">Links</h5>

          <ul class="list-unstyled mb-0">
            <li>
              <a class="text-body" href="#!">Link 1</a>
            </li>
            <li>
              <a class="text-body" href="#!">Link 2</a>
            </li>
            <li>
              <a class="text-body" href="#!">Link 3</a>
            </li>
            <li>
              <a class="text-body" href="#!">Link 4</a>
            </li>
          </ul>
        </div>
      -->
        
        <!--Grid column-->

        <!--Grid column
        <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
          <h5 class="text-uppercase">Links</h5>

          <ul class="list-unstyled mb-0">
            <li>
              <a class="text-body" href="#!">Link 1</a>
            </li>
            <li>
              <a class="text-body" href="#!">Link 2</a>
            </li>
            <li>
              <a class="text-body" href="#!">Link 3</a>
            </li>
            <li>
              <a class="text-body" href="#!">Link 4</a>
            </li>
          </ul>
        </div>
      -->
        <!--Grid column-->

        <!--Grid column
        <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
          <h5 class="text-uppercase">Links</h5>

          <ul class="list-unstyled mb-0">
            <li>
              <a class="text-body" href="#!">Link 1</a>
            </li>
            <li>
              <a class="text-body" href="#!">Link 2</a>
            </li>
            <li>
              <a class="text-body" href="#!">Link 3</a>
            </li>
            <li>
              <a class="text-body" href="#!">Link 4</a>
            </li>
          </ul>
        </div>
      -->
        <!--Grid column-->

        <!--Grid column
        <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
          <h5 class="text-uppercase">Links</h5>

          <ul class="list-unstyled mb-0">
            <li>
              <a class="text-body" href="#!">Link 1</a>
            </li>
            <li>
              <a class="text-body" href="#!">Link 2</a>
            </li>
            <li>
              <a class="text-body" href="#!">Link 3</a>
            </li>
            <li>
              <a class="text-body" href="#!">Link 4</a>
            </li>
          </ul>
        </div>
      -->
        <!--Grid column-->
      </div>
      <!--Grid row-->
    </section>
    <!-- Section: Links -->
  </div>
  <!-- Grid container -->

  <!-- Copyright -->
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.05);">
    © 2024 Copyright
    <a class="text-reset fw-bold" href="https://lanchesgulao.com.br.com/">lanches gulão</a>
  </div>
  <!-- Copyright -->
  {% endcache %}
</footer>
<!-- Footer -->
  </body>
  {% block js_script %}{% endblock %}
  {% cache 3600 cache_Script-2 %}
  <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>

  <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js" integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>
  {% endcache %}
</html>