imersaoPython/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/clearcache/', include('clearcache.urls')),
    path('admin/', admin.site.urls),
    path("",include('produto.urls')),
    path("pedido",include('pedido.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls)),]

pedido/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'Pedido'

urlpatterns = [
    path("finalizar_pedido/", views.finalizar_pedido, name='finalizar_pedido'),
    path("validaCupom/", views.validaCupom, name='validaCupom'),
    path("freteBairro/", views.freteBairro, name='freteBairro'),
    path("novo/",views.novo,name='novo'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pedido/models.py
from django.db import models
from datetime import datetime
from produto.models import Produto,Bairro


class CupomDesconto(models.Model):
    codigo = models.CharField(max_length=8, unique=True)
    desconto = models.FloatField()
    usos = models.IntegerField(default=0)
    ativo = models.BooleanField(default=True)

    def __str__(self):
        return self.codigo


class Pedido(models.Model):
    usuario = models.CharField(max_length=200)
    total = models.FloatField()
    troco = models.CharField(blank=True, max_length=20)
    cupom = models.ForeignKey(CupomDesconto, null=True, blank=True, on_delete=models.DO_NOTHING)
    pagamento = models.CharField(max_length=20)
    ponto_referencia = models.CharField(max_length=2000, blank=True)
    data = models.DateTimeField(default=datetime.now())
    cep = models.CharField(max_length=50, blank=True)
    rua = models.CharField(max_length=200)
    numero = models.CharField(max_length=10)
    bairro = models.ForeignKey(Bairro, on_delete=models.DO_NOTHING)
    telefone = models.CharField(max_length=30)
    entregue = models.BooleanField(default=False)

    def __str__(self):
        return self.usuario


class ItemPedido(models.Model):
    pedido = models.ForeignKey(Pedido, on_delete=models.CASCADE)
    produto = models.ForeignKey(Produto, on_delete=models.CASCADE)
    quantidade = models.IntegerField()
    preco = models.FloatField()
    descricao = models.TextField()
    adicionais = models.TextField()

pedido/views.py
import json
from django.views.decorators.cache import cache_page
from django.shortcuts import redirect, render
from django.http import HttpResponse
from .models import Pedido, ItemPedido, CupomDesconto
from produto.views import get_status,get_categorias_com_contagem,get_status
from produto.models import Produto, Categoria,Bairro,Bairro
from django.contrib.messages import constants
from django.contrib import messages
from django.db import transaction
from django.core.cache import cache
from django.db.models import Count
import datetime
import logging

logger = logging.getLogger('Aplicacao')

def get_categorias_com_contagem():
    cached_categorias = cache.get('all_categorias_com_contagem')
    if cached_categorias is None:
        categorias = Categoria.objects.annotate(quantidade=Count('produto')).values('id', 'categoria', 'quantidade')
        cached_categorias = [{'id': cat['id'], 'categoria': cat['categoria'], 'quantidade': cat['quantidade']} for cat in categorias]
        cache.set('all_categorias_com_contagem', cached_categorias, timeout=1800)
    return cached_categorias

@transaction.atomic
def finalizar_pedido(request):
    status = get_status()
    if request.method == "GET":
        categorias = get_categorias_com_contagem()
        bairros = Bairro.objects.all()
        total = sum([float(i['preco']) for i in request.session['carrinho']])
        return render(request, 'finalizar_pedido.html', {'carrinho': len(request.session['carrinho']),
                                                         'categorias': categorias,
                                                         'total': total,
                                                         'bairros':bairros,
                                                         'status':status,
                                                         })
    else:
        if len(request.session['carrinho']) > 0:
            x = request.POST
            total = sum([float(i['preco']) for i in request.session['carrinho']])
            cupom = CupomDesconto.objects.filter(codigo=x['cupom'])
            cupom_salvar = None
            if len(cupom) > 0 and cupom[0].ativo:
                total = total - ((total * cupom[0].desconto) / 100)
                cupom[0].usos += 1
                cupom[0].save()
                cupom_salvar = cupom[0]

            carrinho = request.session.get('carrinho')
            listaCarrinho = []
            for i in carrinho:
                listaCarrinho.append({
                    'produto': Produto.objects.filter(id=i['id_produto'])[0],
                    'observacoes': i['observacoes'],
                    'preco': i['preco'],
                    'adicionais': i['adicionais'],
                    'quantidade': i['quantidade'],
                })

            lambda_func_troco = lambda x: int(x['troco_para']) - total if not x['troco_para'] == '' else ""
            lambda_func_pagamento = lambda x: 'Cartão' if x['meio_pagamento'] == '2' else 'Dinheiro'
            pedido = Pedido(usuario=x['nome'],
                            total=total,
                            troco=lambda_func_troco(x),
                            cupom=cupom_salvar,
                            pagamento=lambda_func_pagamento(x),
                            ponto_referencia=x['pt_referencia'],
                            cep=x['cep'],
                            rua=x['rua'],
                            numero=x['numero'],
                            bairro=Bairro.objects.get(id=x['bairro']),
                            telefone=x['telefone'],
                            )
            pedido.save()

            ItemPedido.objects.bulk_create(
                ItemPedido(
                    pedido=pedido,
                    produto=v['produto'],
                    quantidade=v['quantidade'],
                    preco=v['preco'],
                    descricao=v['observacoes'],
                    adicionais=str(v['adicionais'])
                ) for v in listaCarrinho

            )

            request.session['carrinho'].clear()
            request.session.save()
            return render(request, 'pedido_realizado.html')
        else:
            logger.warning(f'Escolha ao menos um produto antes de efetuar a compra!'+str(datetime.datetime.now())+' horas!')
            messages.add_message(request, constants.ERROR, 'Escolha ao menos um produto antes de efetuar a compra!')
            return redirect('/pedidofinalizar_pedido/')


@cache_page(60 * 100)
@transaction.atomic
def validaCupom(request):
    data = json.loads(request.body)
    codigo = data.get('cupom')
    cupom = CupomDesconto.objects.filter(codigo = codigo)
    if len(cupom) > 0 and cupom[0].ativo:
        desconto = cupom[0].desconto
        total = sum([float(i['preco']) for i in request.session['carrinho']])
        total_com_desconto = total - ((total*desconto)/100)
        data_json = json.dumps({'status': 0,
                                'desconto': desconto,
                                'total_com_desconto': str(total_com_desconto).replace('.', ',')

                                })
     
        return HttpResponse(data_json)
    else:
        logger.critical(f'erro ao validar o cupom'+str(datetime.datetime.now())+' horas!')
        return HttpResponse(json.dumps({'status': 1}))


@cache_page(60 * 100)
@transaction.atomic
def freteBairro(request):
    data = json.loads(request.body)
    id_bairro = data.get('bairro')
    if id_bairro !='0':
        bairro = Bairro.objects.get(id=id_bairro)
        data_json =json.dumps({'status': 0,
                                        'frete': bairro.Frete,
                                        })
        return HttpResponse(data_json)
    else:
        logger.critical(f'erro ao validar o bairro'+str(datetime.datetime.now())+' horas!')
        return HttpResponse(json.dumps({'status': 1}))

def novo(request):
    status = get_status()
    categorias = get_categorias_com_contagem()
    produtos={}

    for categoria in categorias:
        produtos[categoria['id'],categoria['categoria']]=Produto.objects.filter(ativo=True,categoria=categoria['id']).only('id', 'nome_produto', 'img', 'descricao','promocao','preco').order_by('-id')

    return render(request,'novo_html',{'produtos':produtos,
                                       'status':status,
                                       })

pedido/templates/finalizar_pedido.html
{% extends 'base.html'%}
{% load static %}
{% load cache %}

{% block 'title' %}
Checkout
{% endblock %}
{% block 'head' %}

<script>
    document.addEventListener("DOMContentLoaded", function() {
        function limpa_formulario_cep() {
            // Limpa valores do formulário de cep.
            document.getElementById("rua").value = "";
            document.getElementById("inputbairro").value = "";
        }

        // Quando o campo cep perde o foco.
        document.getElementById("cep").addEventListener("blur", function() {
            // Nova variável "cep" somente com dígitos.
            var cep = this.value.replace(/\D/g, '');

            // Verifica se campo cep possui valor informado.
            if (cep !== "") {
                // Expressão regular para validar o CEP.
                var validacep = /^[0-9]{8}$/;

                // Valida o formato do CEP.
                if(validacep.test(cep)) {
                    // Preenche os campos com "..." enquanto consulta o webservice.
                    document.getElementById("rua").value = "...";
                    document.getElementById("inputbairro").value = "...";

                    // Consulta o webservice viacep.com.br/
                    fetch("https://viacep.com.br/ws/" + cep + "/json/")
                        .then(response => response.json())
                        .then(dados => {
                            if (!("erro" in dados)) {
                                // Atualiza os campos com os valores da consulta.
                                document.getElementById("rua").value = dados.logradouro;
                                document.getElementById("inputbairro").value = dados.bairro;
                            } else {
                                // CEP pesquisado não foi encontrado.
                                limpa_formulario_cep();
                                alert("CEP não encontrado.");
                            }
                        })
                        .catch(error => {
                            console.error("Erro na requisição:", error);
                        });
                } else {
                    // CEP é inválido.
                    limpa_formulario_cep();
                    alert("Formato de CEP inválido.");
                }
            } else {
                // CEP sem valor, limpa formulário.
                limpa_formulario_cep();
            }
        });
    });
</script>

{%endblock%}



{%block 'conteudo'%}
<div class="container">


  <br>
  <h1 class="rosa text-center">Ao clicar em "Efetuar pedido" será confirmado sua compra</h1>
  <hr>
 {% if messages%}
        {% for i in messages%}
        <div class="alert {{i.tags}}" role="alert">
            {{i}}
        </div>
        {%endfor%}
        {%endif%}


    <div class="row">

        <div class="col-sm fundo">

        <form method="POST" action="{% url 'Pedido:finalizar_pedido' %}">{% csrf_token %}

          <br>
          <h3 class="rosa">Nome<span class="importante">*</span>:</h3>
          <input type="text" required="required" class="form-control" placeholder="Nome" name="nome">
          <br>
          <h3 class="rosa">Cep<span class="importante">*</span>:</h3>
          <input type="text" class="form-control" required="required" data-mask='00000-000' id="cep" placeholder="CEP" name="cep">
          <br>
          <!-- <h3 class="rosa">Cidade*:</h3>
          <select class="form-control">
            <option selected>Contagem</option>
              <option >Belo Horizonte</option>
              <option >Ribeirao das Neves</option>
          </select>
        -->
          <h3 class="rosa">Rua<span class="importante">*</span>:</h3>
          <input type="text" required="required" class="form-control" placeholder="Rua" id="rua" name="rua">

          <br>
          <h3 class="rosa">Número<span class="importante">*</span>:</h3>
          <input type="text" required="required" class="form-control" placeholder="Número" name="numero">

          <br>
          <h3 class="rosa">Bairro<span class="importante">*</span>:</h3>

          <select class="form-control" required="required" class="form-control" placeholder="Bairro" id="inputbairro" name="bairro" onchange="freteBairro()">
            <option value="0" selected>Selecione seu Bairro</option>
            {% for bairro in bairros %}
              <option value="{{bairro.id}}">{{bairro}}</option>
              {% endfor%}

  
          </select>
          

          <br>
          <h3 class="rosa">Ponto de referência:</h3>
          <input type="text" class="form-control" placeholder="Ponto de referência" name="pt_referencia">

          <br>
          <h3 class="rosa">Telefone<span class="importante">*</span>:</h3>
          <input type="text" required="required" class="form-control" placeholder="Telefone" name="telefone" id="telefone">
          <br>



    </div>

  </div>
  <div class="row">
    <div class="col-sm fundo">

    </div>

    <div class="col-sm fundo">
        <div class="rosa">
            <h4> O pagamento sera realizado no momento da entrega</h4>
        </div>
    </div>


</div>
<hr>
<br>
<div class="row">
    <div class="col-sm fundo">
        <h1 id="total">Total: R$ {{total}}0</h1>
        <p id="msg_frete"></p>
        <h1 id="frete_msg">Frete : {{Bairro}}0</h1>
        <input id="frete" type="text" style="display: none;" name="frete" value="{{Bairro}}0">
    </div>

    <div class="col-sm fundo">
        <input id="inputCupom" class="form-control" type="text" name="cupom" placeholder="Cupom de desconto">
        <p id="msg"></p>
        <br>
        <div id="btnCupom" class="btn btn-secondary" onclick="validaCupom()">Validar cupom</div>
    </div>


</div>
<br>
<br>

<div id="pagamento">

    <h3 class="rosa">Meio de pagamento<span class="importante">*</span>:</h3>
    <select name="meio_pagamento" class="form-control" onchange="javascript:dinheiro(this);">
        <option value="1">Dinheiro / Pix </option>
        <option value="2">Cartão</option>
    </select>

    <div id="troco">
        <h3 class="rosa">troco para</h3>
        <input type="text" class="form-control"  placeholder="ex.:10" name="troco_para">
    </div>
    <br>
    <div class="text-center">
     
    <button onclick="envia()" class="btn btn-success btn-lg loja-fechada">Efetuar pedido!</button>
</div>
</div>

</form>

</div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.16/jquery.mask.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/imask/6.0.6/imask.min.js"></script>
<script>
    // Selecione o campo de entrada de telefone
    var telefoneInput = document.getElementById('telefone');

    // Crie uma máscara para o número de telefone
    var telefoneMask = IMask(telefoneInput, {
        mask: '(00)00000-0000'  // Define a máscara desejada
    });
</script>

<script>
    function validaCupom() {
        const cupom = document.getElementById('inputCupom').value;
        fetch("{% url 'Pedido:validaCupom'%}", {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'X-CSRFToken': '{{ csrf_token }}'
            },
            body: JSON.stringify({ cupom: cupom })
        })
        .then(response => response.json())
        .then(resposta => {
            const div_total = document.getElementById('total');
            const msg = document.getElementById('msg');
            if (resposta['status'] == 1) {
                div_total.innerHTML = 'Total: R$ {{total}}0';
                msg.innerHTML = "Cupom inválido Ou Inativo";
                msg.style.color = 'red';
            } else {
                div_total.innerHTML = 'De: <s style="color: red;">R$ {{total}}0</s> Por R$' +  resposta['total_com_desconto'] + '0';
                msg.innerHTML = resposta['desconto'] + "% aplicado com sucesso";
                msg.style.color = 'green';
            }
        })
        .catch(error => console.error('Erro:', error));
    }
    </script>
    

<script>
    function freteBairro(){
        bairro = document.getElementById('inputbairro').value
        fetch("{% url 'Pedido:freteBairro'%}", {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'X-CSRFToken': '{{ csrf_token }}'
            },
            body: JSON.stringify({ bairro: bairro })
        })
        .then(response => response.json())
        .then(resposta => {
            const frete_msg = document.getElementById('frete_msg');
            const msg_frete = document.getElementById('msg_frete');
            if (resposta['status'] == 1) {
            } else {
                frete_msg.innerHTML  ='';
                frete_msg.innerHTML = 'Frete : R$' +  resposta['frete'];
                msg_frete.style.color = 'green';
            }
        })
        .catch(error => console.error('Erro:', error));
    }
    </script>

{%endblock%}

pedido/templates/pedido_realizado.html
{% extends 'base.html'%}

{% block 'conteudo' %}
<div class="alert alert-success text-center" role="alert">
    Seu pedido foi realizado com sucesso
  </div>
{%endblock%}